# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-11-02 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
