# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-11-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0002_auto_20211102_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='dumb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='fat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='stupid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
